Today, I learned how to make a proper conversation and including variables, Ms. Terkper told us to only do half of the Replit challenge today, so we can work on our MicroBit.
myName = input("What's your name?: ")
print ("My name is", myName)
print ("That is a nice name!")
myAge = input("How old are you?: ")
print ("I am", myAge)
print ("Ohh.. That's a little old.. Just jokes!")
myFood = input("What about... your favourite food?: ")
print ("I like", myFood)
print ("Thats a good choice! I personally, like tteok bokki, which are Korean spicy rice cakes!")
myHobby = input("Any hobbies?: ")
print ("I like to", myHobby)
print ("Cool!! I guess you're one of the unqiue ones.")
myEthnicity = input("Well, where you from???: ")
print ("I'm from", myEthnicity) 
print ("I've never been there before..")
print ("Well, it was nice getting to know you,", myName)
print ("Bye!")
